#!/bin/bash

set -eu

if [ $# -eq 0 ]
then
        echo "usage: $0 <filename>"
        exit 1
fi

FILEPATH="$1"
DIR=$(dirname "$FILEPATH")
FILE=$(basename "$FILEPATH")

pushd "$DIR" > /dev/null
touch "$FILE"

go build -gcflags='-m' 2>&1 | \
        grep ' to heap' | \
        grep "$FILE"

popd > /dev/null
